name: End-to-End Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Pull and Run Database Docker Image
      - name: Run MySQL database service
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/raisehub_database:latest
          docker run -d --name mysql \
            -p 3306:3306 \
            --env MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            --env MYSQL_DATABASE=crowdfund_db \
            ${{ secrets.DOCKER_USERNAME }}/raisehub_database:latest

      # Step 3.1: Wait for MySQL to Start and Verify Service
      - name: Wait for MySQL Service to Start
        run: |
          for i in {1..10}; do
            docker exec mysql mysqladmin ping -h 127.0.0.1 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} && break
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done || (echo "MySQL failed to start" && exit 1)

      - name: Debug MySQL Logs
        if: failure()
        run: |
          docker logs mysql

      # Step 4: Pull and Run Backend Docker Image
      - name: Run backend service
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/raisehub_backend:latest
          docker run -d --name backend \
            -p 8080:8080 \
            --env DATABASE_URL=mysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@127.0.0.1:3306/crowdfund_db \
            ${{ secrets.DOCKER_USERNAME }}/raisehub_backend:latest

      # Step 4.1: Wait for Backend to Start and Verify Service
      - name: Wait for Backend Service to Start
        run: |
          for i in {1..10}; do
            curl -sSf http://localhost:8080/health && break
            echo "Waiting for Backend to be ready..."
            sleep 5
          done || (echo "Backend failed to start" && exit 1)

      # Step 5: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          npm install

      # Step 6: Start the frontend application
      - name: Start frontend server
        run: |
          npm run build
          npm run start &
        env:      
          REACT_APP_API_URL: http://localhost:8080 # Set backend API URL

      # Step 7: Wait for frontend service
      - name: Wait for Frontend Service
        run: |
          npx wait-on http://localhost:3000

      # Step 8: Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          config-file: frontend/cypress.config.js
